INSERT INTO public.news (id, title, content) VALUES (2, 'second', 'some content 2');
INSERT INTO public.news (id, title, content) VALUES (3, 'third', 'some content 3');
INSERT INTO public.news (id, title, content) VALUES (4, 'fourth', 'some content 4');
INSERT INTO public.news (id, title, content) VALUES (5, 'fifth', 'some content 5');
INSERT INTO public.news (id, title, content) VALUES (6, 'sixth', 'some content 6');
INSERT INTO public.news (id, title, content) VALUES (8, 'eightth', 'some content 8');
INSERT INTO public.news (id, title, content) VALUES (9, 'nineth', 'some content 9');
INSERT INTO public.news (id, title, content) VALUES (10, 'tenth', 'some content 10');
INSERT INTO public.news (id, title, content) VALUES (11, 'eleventh', 'some content 11');
INSERT INTO public.news (id, title, content) VALUES (12, 'twelveth', 'some content 12');
INSERT INTO public.news (id, title, content) VALUES (13, 'thirteenth', 'some content 13');
INSERT INTO public.news (id, title, content) VALUES (14, 'fourteenth', 'some content 14');
INSERT INTO public.news (id, title, content) VALUES (15, 'fiveteenth', 'some content 15');
INSERT INTO public.news (id, title, content) VALUES (16, 'sexteenth', 'some content 16');
INSERT INTO public.news (id, title, content) VALUES (17, 'seventeenth', 'some content 17');
INSERT INTO public.news (id, title, content) VALUES (18, 'eighteenth', 'some content 18');
INSERT INTO public.news (id, title, content) VALUES (19, 'nineteenth', 'some content 19');
INSERT INTO public.news (id, title, content) VALUES (20, 'Lorem ipsum kekoslav', 'Dolor sit amet <b>foo</b>');
INSERT INTO public.news (id, title, content) VALUES (7, 'Lorem ipsum kekoslav123', 'Dolor123 sit amet <b>foo</b>');
INSERT INTO public.news (id, title, content) VALUES (1, 'Lorem ipsum kekoslav123', 'Dolor123 sit amet <b>foo</b>');
INSERT INTO public.news_categories (news_id, category_id) VALUES (2, 6);
INSERT INTO public.news_categories (news_id, category_id) VALUES (19, 4);
INSERT INTO public.news_categories (news_id, category_id) VALUES (4, 19);
INSERT INTO public.news_categories (news_id, category_id) VALUES (6, 6);
INSERT INTO public.news_categories (news_id, category_id) VALUES (5, 5);
INSERT INTO public.news_categories (news_id, category_id) VALUES (11, 1);
INSERT INTO public.news_categories (news_id, category_id) VALUES (14, 1);
INSERT INTO public.news_categories (news_id, category_id) VALUES (17, 1);
INSERT INTO public.news_categories (news_id, category_id) VALUES (20, 1);
INSERT INTO public.news_categories (news_id, category_id) VALUES (3, 2);
INSERT INTO public.news_categories (news_id, category_id) VALUES (12, 2);
INSERT INTO public.news_categories (news_id, category_id) VALUES (15, 2);
INSERT INTO public.news_categories (news_id, category_id) VALUES (18, 2);
INSERT INTO public.news_categories (news_id, category_id) VALUES (8, 8);
INSERT INTO public.news_categories (news_id, category_id) VALUES (10, 3);
INSERT INTO public.news_categories (news_id, category_id) VALUES (9, 9);
INSERT INTO public.news_categories (news_id, category_id) VALUES (13, 3);
INSERT INTO public.news_categories (news_id, category_id) VALUES (16, 3);
INSERT INTO public.news_categories (news_id, category_id) VALUES (7, 46);
INSERT INTO public.news_categories (news_id, category_id) VALUES (1, 4);
INSERT INTO public.news_categories (news_id, category_id) VALUES (1, 5);
INSERT INTO public.news_categories (news_id, category_id) VALUES (1, 6);
